name: Twitch Refresh Every Hour

on:
  schedule:
    - cron: '0 * * * *' # 매시간 0분마다 실행
  workflow_dispatch: # 수동 실행 버튼도 허용

jobs:
  refresh-twitch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npx ts-node --project tsconfig.scripts.json src/scripts/twitch/utils/truncateTables.ts
      - run: npx ts-node --project tsconfig.scripts.json src/scripts/twitch/discoverTwitchStreamers.ts --limit=100 --language=ko
