name: Twitch Refresh Every Hour

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  refresh-twitch:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
      TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npx ts-node --project tsconfig.scripts.json src/scripts/twitch/utils/truncateTables.ts
      - run: npx ts-node --project tsconfig.scripts.json src/scripts/twitch/discoverTwitchStreamers.ts --limit=100 --language=ko
